name: 🧪 Run tests & checks on new PR or master merge

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    name: 🥼 Test
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🧪 Test Project
        run: |
          npm install
          npm run check
